project_id = "default"

[functions.inngest]
verify_jwt = false

[functions.webhook-web]
verify_jwt = false

[functions.webhook-approval]
verify_jwt = false

[functions.webhook-whatsapp]
verify_jwt = false
